require('dotenv').config();
const mongoose = require('mongoose');
const Recipe = require('./models/Recipe');
const connectDB = require('./db');

const recipes = [
  { name: "Masala Dosa", country: "India", type: "Vegetarian", time: 30, img: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80", ingredients: ["Rice batter", "Urad dal", "Potato", "Onion", "Mustard seeds", "Spices"], steps: ["Prepare dosa batter and ferment it.", "Cook potato masala with onion and spices.", "Spread batter on hot tawa.", "Add masala filling inside.", "Fold and serve hot."] },
  { name: "Paneer Butter Masala", country: "India", type: "Vegetarian", time: 35, img: "https://images.unsplash.com/photo-1690401767645-595de0e0e5f8?q=80&w=2026&auto=format&fit=crop", ingredients: ["Paneer", "Tomato", "Butter", "Cream", "Onion", "Spices"], steps: ["Cook onion and tomato gravy.", "Blend it into a smooth paste.", "Add butter, cream, and spices.", "Put paneer cubes into gravy.", "Cook for a few minutes and serve."] },
  { name: "Butter Chicken", country: "India", type: "Non-Vegetarian", time: 40, img: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=1170&auto=format&fit=crop", ingredients: ["Chicken", "Butter", "Tomato puree", "Cream", "Garlic", "Spices"], steps: ["Marinate and cook the chicken.", "Prepare buttery tomato gravy.", "Add cream and spices.", "Mix chicken into the gravy.", "Simmer and serve with naan or rice."] },
  { name: "Margherita Pizza", country: "Italy", type: "Vegetarian", time: 25, img: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80", ingredients: ["Pizza dough", "Tomato sauce", "Mozzarella", "Basil", "Olive oil"], steps: ["Roll out the pizza dough.", "Spread tomato sauce on top.", "Add mozzarella cheese.", "Bake until crisp and golden.", "Top with basil and serve."] },
  { name: "Pasta Alfredo", country: "Italy", type: "Vegetarian", time: 20, img: "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?auto=format&fit=crop&w=800&q=80", ingredients: ["Pasta", "Butter", "Cream", "Parmesan cheese", "Garlic"], steps: ["Boil pasta until soft.", "Prepare sauce with butter, cream, and garlic.", "Add parmesan cheese to sauce.", "Mix pasta into the sauce.", "Serve warm."] },
  { name: "Chicken Lasagna", country: "Italy", type: "Non-Vegetarian", time: 45, img: "https://images.unsplash.com/photo-1619895092538-128341789043?auto=format&fit=crop&w=800&q=80", ingredients: ["Lasagna sheets", "Chicken", "Tomato sauce", "Cheese", "White sauce"], steps: ["Cook chicken filling with sauce.", "Layer lasagna sheets, filling, and sauces.", "Add cheese on top.", "Bake until golden.", "Cool slightly and serve."] },
  { name: "Sushi", country: "Japan", type: "Non-Vegetarian", time: 25, img: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80", ingredients: ["Sushi rice", "Nori", "Fish", "Cucumber", "Soy sauce"], steps: ["Cook and season sushi rice.", "Place nori sheet on mat.", "Spread rice over nori.", "Add fillings and roll tightly.", "Cut into pieces and serve."] },
  { name: "Ramen", country: "Japan", type: "Non-Vegetarian", time: 30, img: "https://images.unsplash.com/photo-1557872943-16a5ac26437e?auto=format&fit=crop&w=800&q=80", ingredients: ["Ramen noodles", "Broth", "Egg", "Chicken", "Spring onion"], steps: ["Prepare flavorful broth.", "Cook ramen noodles.", "Add noodles to the broth.", "Top with egg, chicken, and spring onion.", "Serve hot."] },
  { name: "Vegetable Tempura", country: "Japan", type: "Vegetarian", time: 15, img: "https://images.unsplash.com/photo-1713810979948-bfde10823f4a?q=80&w=1170&auto=format&fit=crop", ingredients: ["Vegetables", "Flour", "Cornstarch", "Cold water", "Oil"], steps: ["Cut vegetables into pieces.", "Prepare light tempura batter.", "Dip vegetables into batter.", "Deep fry until crisp.", "Serve immediately."] },
  { name: "Tacos", country: "Mexico", type: "Non-Vegetarian", time: 15, img: "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?auto=format&fit=crop&w=800&q=80", ingredients: ["Tortilla", "Chicken", "Lettuce", "Cheese", "Salsa"], steps: ["Cook the chicken with seasoning.", "Warm the tortillas.", "Fill with chicken, lettuce, cheese, and salsa.", "Fold and serve."] },
  { name: "Guacamole", country: "Mexico", type: "Gluten-Free", time: 10, img: "https://plus.unsplash.com/premium_photo-1681406689563-247f41ec5ac6?q=80&w=687&auto=format&fit=crop", ingredients: ["Avocado", "Onion", "Tomato", "Lime", "Salt", "Coriander"], steps: ["Mash ripe avocado.", "Add chopped onion and tomato.", "Mix in lime juice and salt.", "Add coriander and mix well.", "Serve fresh."] },
  { name: "Quesadilla", country: "Mexico", type: "Vegetarian", time: 20, img: "https://images.unsplash.com/photo-1618040996337-56904b7850b9?auto=format&fit=crop&w=800&q=80", ingredients: ["Tortilla", "Cheese", "Bell peppers", "Onion", "Butter"], steps: ["Place cheese and vegetables inside tortilla.", "Fold tortilla in half.", "Cook on pan until golden.", "Cut into slices and serve."] },
  { name: "Koshari", country: "Egypt", type: "Vegetarian", time: 35, img: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=800&q=80", ingredients: ["Rice", "Lentils", "Pasta", "Chickpeas", "Tomato sauce", "Fried onions"], steps: ["Cook rice, lentils, and pasta separately.", "Mix them together in a bowl.", "Top with tomato sauce and chickpeas.", "Garnish with crispy fried onions and serve."] },
  { name: "Falafel (Ta'ameya)", country: "Egypt", type: "Vegetarian", time: 20, img: "https://images.unsplash.com/photo-1680405531955-8b4981bb1b0c?auto=format&fit=crop&w=800&q=80", ingredients: ["Fava beans", "Parsley", "Coriander", "Garlic", "Onion", "Spices", "Oil"], steps: ["Soak and grind fava beans with herbs and spices.", "Shape the mixture into small balls or patties.", "Deep fry until crispy and golden brown.", "Serve hot with bread or dip."] },
  { name: "Chicken Shawarma", country: "Egypt", type: "Non-Vegetarian", time: 25, img: "https://images.unsplash.com/photo-1676300187013-7540d4e9440d?auto=format&fit=crop&w=800&q=80", ingredients: ["Chicken", "Yogurt", "Garlic", "Spices", "Pita bread", "Vegetables"], steps: ["Marinate chicken with yogurt, garlic, and spices.", "Cook the chicken until tender and slightly crispy.", "Slice into thin strips.", "Wrap in pita bread with vegetables and sauce."] },
  { name: "Karjalanpiirakka (Karelian Pies)", country: "Finland", type: "Vegetarian", time: 45, img: "https://i.postimg.cc/qRq692wT/Karjalanpiirakka-20060227.jpg", ingredients: ["Rye flour", "Rice", "Milk", "Butter", "Salt"], steps: ["Prepare rice porridge using rice and milk.", "Make dough using rye flour and water.", "Roll dough into thin oval shapes.", "Fill with rice porridge and fold edges.", "Bake until golden and serve with butter."] },
  { name: "Lohikeitto (Salmon Soup)", country: "Finland", type: "Non-Vegetarian", time: 30, img: "https://i.postimg.cc/MphWWVqN/images.webp", ingredients: ["Salmon", "Potatoes", "Carrots", "Onion", "Cream", "Dill"], steps: ["Boil potatoes, carrots, and onions in water.", "Add salmon pieces and cook gently.", "Pour in cream and simmer.", "Season with salt and dill.", "Serve hot."] },
  { name: "Mustikkapiirakka (Blueberry Pie)", country: "Finland", type: "Vegetarian", time: 40, img: "https://images.unsplash.com/photo-1572526474144-98925b3468df?auto=format&fit=crop&w=800&q=80", ingredients: ["Blueberries", "Flour", "Sugar", "Butter", "Eggs", "Milk"], steps: ["Prepare the pie crust using flour, butter, and sugar.", "Spread fresh blueberries over the crust.", "Mix eggs and milk to make a filling.", "Pour the mixture over the blueberries.", "Bake until set and golden."] },
  { name: "Kimchi", country: "South Korea", type: "Vegetarian", time: 60, img: "https://images.unsplash.com/photo-1583224964978-2257b960c3d3?auto=format&fit=crop&w=800&q=80", ingredients: ["Napa cabbage", "Garlic", "Ginger", "Chili flakes", "Salt", "Fish sauce (optional)"], steps: ["Salt the cabbage and let it rest to soften.", "Prepare a paste with garlic, ginger, and chili flakes.", "Mix the cabbage with the paste thoroughly.", "Store in a container and let it ferment.", "Serve as a side dish."] },
  { name: "Bibimbap", country: "South Korea", type: "Non-Vegetarian", time: 30, img: "https://images.unsplash.com/photo-1718777791239-c473e9ce7376?auto=format&fit=crop&w=800&q=80", ingredients: ["Rice", "Beef", "Vegetables", "Egg", "Gochujang (chili paste)", "Sesame oil"], steps: ["Cook rice and prepare assorted vegetables.", "Cook beef with seasoning.", "Place rice in a bowl and arrange toppings on top.", "Add a fried egg and gochujang.", "Mix well before eating."] },
  { name: "Tteokbokki", country: "South Korea", type: "Vegetarian", time: 20, img: "https://images.unsplash.com/photo-1730900737734-f159ca5640c3?auto=format&fit=crop&w=800&q=80", ingredients: ["Rice cakes", "Gochujang", "Sugar", "Garlic", "Fish cakes (optional)", "Water"], steps: ["Boil water and add gochujang, sugar, and garlic.", "Add rice cakes and cook until soft.", "Add fish cakes if desired.", "Simmer until sauce thickens.", "Serve hot."] },
  { name: "Croissant", country: "France", type: "Vegetarian", time: 60, img: "https://images.unsplash.com/photo-1623334044303-241021148842?auto=format&fit=crop&w=800&q=80", ingredients: ["Flour", "Butter", "Milk", "Sugar", "Yeast"], steps: ["Prepare dough using flour, yeast, milk, and sugar.", "Layer with butter and fold multiple times.", "Shape into crescent forms.", "Bake until golden and flaky.", "Serve warm."] },
  { name: "Ratatouille", country: "France", type: "Vegetarian", time: 40, img: "https://images.unsplash.com/photo-1572453800999-e8d2d1589b7c?auto=format&fit=crop&w=800&q=80", ingredients: ["Eggplant", "Zucchini", "Tomatoes", "Onion", "Garlic", "Herbs"], steps: ["Chop all vegetables evenly.", "Sauté onions and garlic.", "Add vegetables and cook slowly.", "Season with herbs.", "Serve hot."] },
  { name: "Coq au Vin", country: "France", type: "Non-Vegetarian", time: 50, img: "https://i.postimg.cc/Vv8vzTP7/images.jpg", ingredients: ["Chicken", "Red wine", "Mushrooms", "Onion", "Garlic", "Herbs"], steps: ["Marinate chicken in wine.", "Cook chicken until browned.", "Add vegetables and herbs.", "Simmer slowly in wine sauce.", "Serve hot."] },
  { name: "Bratwurst", country: "Germany", type: "Non-Vegetarian", time: 25, img: "https://images.unsplash.com/photo-1695089026763-0d984cbf7088?auto=format&fit=crop&w=800&q=80", ingredients: ["Sausages", "Bread", "Mustard", "Onion"], steps: ["Grill or pan-fry the sausages.", "Toast the bread.", "Place sausage in bread.", "Add mustard and onions.", "Serve hot."] },
  { name: "Pretzel", country: "Germany", type: "Vegetarian", time: 40, img: "https://i.postimg.cc/yN0z7N1j/pretzel-salts-shape-is-flatter-than-regular-salt-1689979496.jpg", ingredients: ["Flour", "Yeast", "Water", "Salt", "Baking soda"], steps: ["Prepare dough using flour and yeast.", "Shape into pretzel form.", "Boil briefly in baking soda water.", "Bake until golden brown.", "Sprinkle salt and serve."] },
  { name: "Schnitzel", country: "Germany", type: "Non-Vegetarian", time: 30, img: "https://i.postimg.cc/rsmbRyTy/Breitenlesau-Krug-Brau-Schnitzel.jpg", ingredients: ["Meat cutlet", "Eggs", "Breadcrumbs", "Flour", "Oil"], steps: ["Flatten the meat.", "Coat with flour, egg, and breadcrumbs.", "Fry until crispy.", "Serve with lemon or sides."] },
  { name: "Pho", country: "Vietnam", type: "Non-Vegetarian", time: 45, img: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=800&q=80", ingredients: ["Rice noodles", "Beef", "Broth", "Herbs", "Spices"], steps: ["Prepare broth with spices.", "Cook rice noodles.", "Add beef slices.", "Pour hot broth over noodles.", "Garnish with herbs and serve."] },
  { name: "Banh Mi", country: "Vietnam", type: "Non-Vegetarian", time: 20, img: "https://i.postimg.cc/CM9TnDR6/banh-mi-with-grilled-pork1-1663331872.avif", ingredients: ["Baguette", "Meat", "Vegetables", "Pickles", "Sauce"], steps: ["Slice the baguette.", "Add cooked meat.", "Fill with vegetables and pickles.", "Add sauce.", "Serve fresh."] },
  { name: "Spring Rolls", country: "Vietnam", type: "Vegetarian", time: 25, img: "https://i.postimg.cc/y6Mt8HGX/24239-vietnamese-fresh-spring-rolls-VAT-003-4x3-02closeup-aa51c09981414dab9b14007c78a9bbab.jpg", ingredients: ["Rice paper", "Vegetables", "Noodles", "Herbs"], steps: ["Soften rice paper in water.", "Place vegetables and noodles inside.", "Roll tightly.", "Serve with dipping sauce."] },
  { name: "Pad Thai", country: "Thailand", type: "Non-Vegetarian", time: 30, img: "https://images.unsplash.com/photo-1655091273851-7bdc2e578a88?auto=format&fit=crop&w=800&q=80", ingredients: ["Rice noodles", "Shrimp", "Eggs", "Peanuts", "Bean sprouts", "Tamarind sauce"], steps: ["Soak and cook rice noodles.", "Stir-fry shrimp and eggs.", "Add noodles and sauce.", "Mix with vegetables and peanuts.", "Serve hot."] },
  { name: "Green Curry", country: "Thailand", type: "Non-Vegetarian", time: 35, img: "https://i.postimg.cc/TwRm9phZ/Green-curry-chicken-sq-2.jpg", ingredients: ["Chicken", "Coconut milk", "Green curry paste", "Vegetables", "Basil"], steps: ["Cook curry paste in a pan.", "Add coconut milk and stir.", "Add chicken and vegetables.", "Simmer until cooked.", "Serve with rice."] },
  { name: "Mango Sticky Rice", country: "Thailand", type: "Vegetarian", time: 25, img: "https://i.postimg.cc/NfWHnN55/AR-150313-thai-sweet-sticky-rice-with-mango-khao-neeo-mamuang-ddmfs-1x2-hero-0e40dae3393645e28e6ca20.jpg", ingredients: ["Sticky rice", "Mango", "Coconut milk", "Sugar"], steps: ["Cook sticky rice.", "Prepare coconut milk sauce.", "Slice fresh mango.", "Serve rice with mango and sauce."] },
  { name: "Paella", country: "Spain", type: "Non-Vegetarian", time: 45, img: "https://images.unsplash.com/photo-1623961990059-28356e226a77?auto=format&fit=crop&w=800&q=80", ingredients: ["Rice", "Seafood", "Saffron", "Vegetables", "Chicken"], steps: ["Cook rice with saffron.", "Add seafood and chicken.", "Mix with vegetables.", "Cook until flavors combine.", "Serve hot."] },
  { name: "Tortilla Española", country: "Spain", type: "Non-Vegetarian", time: 30, img: "https://i.postimg.cc/brZZCbP7/213226-tortilla-espanola-VAT-007-4x3-70f5f39a1d884375b7a0a5b8ef963e18.jpg", ingredients: ["Potatoes", "Eggs", "Onion", "Olive oil"], steps: ["Slice and fry potatoes.", "Mix with beaten eggs.", "Cook in a pan until set.", "Flip and cook the other side.", "Serve warm."] },
  { name: "Churros", country: "Spain", type: "Vegetarian", time: 20, img: "https://i.postimg.cc/2SQVKCpS/ALR-recipe-24700-churros-VAT-hero-03-4x3-a7f6af1860934b0385f84ab9f13f2613.jpg", ingredients: ["Flour", "Water", "Sugar", "Oil"], steps: ["Prepare dough with flour and water.", "Pipe into hot oil.", "Fry until golden.", "Coat with sugar.", "Serve with chocolate."] },
  { name: "Welsh Rarebit", country: "Wales", type: "Vegetarian", time: 20, img: "https://i.postimg.cc/3NTnWBK8/perfect-welsh-rarebit-featured-1.jpg", ingredients: ["Bread", "Cheese", "Mustard", "Butter"], steps: ["Toast the bread.", "Melt cheese with butter and mustard.", "Spread over toast.", "Grill until bubbly.", "Serve hot."] },
  { name: "Cawl", country: "Wales", type: "Non-Vegetarian", time: 40, img: "https://i.postimg.cc/L43VNj9X/cawl-welsh-lamb-soup-71220-1.jpg", ingredients: ["Lamb", "Potatoes", "Carrots", "Leeks", "Onion"], steps: ["Boil lamb with vegetables.", "Simmer until tender.", "Season to taste.", "Serve hot."] },
  { name: "Bara Brith", country: "Wales", type: "Vegetarian", time: 50, img: "https://i.postimg.cc/gJPvK21V/recipe-image-legacy-id-1239459-8-4fbd4b1.jpg", ingredients: ["Flour", "Dried fruits", "Tea", "Sugar"], steps: ["Soak dried fruits in tea.", "Mix with flour and sugar.", "Bake until firm.", "Slice and serve."] },
  { name: "Swedish Meatballs", country: "Sweden", type: "Non-Vegetarian", time: 30, img: "https://images.unsplash.com/photo-1600688685721-852c38f6e8a6?auto=format&fit=crop&w=800&q=80", ingredients: ["Minced meat", "Onion", "Egg", "Breadcrumbs", "Cream"], steps: ["Mix ingredients and form balls.", "Fry until browned.", "Add cream sauce.", "Serve hot."] },
  { name: "Gravlax", country: "Sweden", type: "Non-Vegetarian", time: 25, img: "https://i.postimg.cc/C1Yqq6fX/simple-homemade-gravlax-recipe-2216618-step-15-288e5b9150154a09b23c3c6c418e7327.jpg", ingredients: ["Salmon", "Salt", "Sugar", "Dill"], steps: ["Cure salmon with salt and sugar.", "Add dill.", "Refrigerate for a day.", "Slice thinly and serve."] },
  { name: "Cinnamon Buns", country: "Sweden", type: "Vegetarian", time: 40, img: "https://i.postimg.cc/1t98tnkx/swedish-cinnamon-buns-3.jpg", ingredients: ["Flour", "Cinnamon", "Sugar", "Butter", "Yeast"], steps: ["Prepare dough.", "Add cinnamon filling.", "Roll and shape.", "Bake until golden.", "Serve warm."] },
  { name: "Chicken Adobo", country: "Philippines", type: "Non-Vegetarian", time: 35, img: "https://images.unsplash.com/photo-1596699917234-1c93c61a1083?auto=format&fit=crop&w=800&q=80", ingredients: ["Chicken", "Soy sauce", "Vinegar", "Garlic", "Bay leaves"], steps: ["Marinate chicken.", "Cook with sauce.", "Simmer until tender.", "Serve hot."] },
  { name: "Pancit", country: "Philippines", type: "Non-Vegetarian", time: 25, img: "https://i.postimg.cc/XqtNwpzV/filipino-pancit-1200.jpg", ingredients: ["Noodles", "Vegetables", "Chicken", "Soy sauce"], steps: ["Cook noodles.", "Stir-fry ingredients.", "Mix together.", "Serve hot."] },
  { name: "Halo-Halo", country: "Philippines", type: "Vegetarian", time: 15, img: "https://i.postimg.cc/SKmS70DF/Halo-Halo-12e653b.jpg", ingredients: ["Ice", "Milk", "Fruits", "Beans", "Sugar"], steps: ["Add ingredients to a bowl.", "Top with ice.", "Pour milk.", "Mix and serve."] },
  { name: "Fish and Chips", country: "New Zealand", type: "Non-Vegetarian", time: 25, img: "https://i.postimg.cc/RCJW0BYy/Fish-and-chips-blackpool.jpg", ingredients: ["Fish fillets", "Potatoes", "Flour", "Oil", "Salt"], steps: ["Cut potatoes into fries.", "Coat fish in flour batter.", "Deep fry fish and chips until golden.", "Season with salt.", "Serve hot."] },
  { name: "Pavlova", country: "New Zealand", type: "Vegetarian", time: 40, img: "https://images.unsplash.com/photo-1702744754798-4a1d980b03e2?auto=format&fit=crop&w=800&q=80", ingredients: ["Egg whites", "Sugar", "Cream", "Fruits"], steps: ["Whip egg whites.", "Bake meringue base.", "Add cream and fruits.", "Serve chilled."] },
  { name: "Meat Pie", country: "New Zealand", type: "Non-Vegetarian", time: 35, img: "https://i.postimg.cc/nhFVqbdZ/Traditional-Chunky-Pepper-Beef-Pies.avif", ingredients: ["Pastry", "Meat", "Gravy"], steps: ["Prepare filling.", "Fill pastry.", "Bake until golden.", "Serve hot."] }
];

const seed = async () => {
  await connectDB();
  await Recipe.deleteMany({});
  await Recipe.insertMany(recipes);
  console.log('All 48 recipes seeded successfully!');
  mongoose.connection.close();
};

seed();